version: '3'
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
    environment:
      - MYSQL_ROOT_PASSWORD=root  #環境変数
    ports:
      - "4306:3306"